# Data Structures (2)

## Python Matrices

*   Python does not have a built-in type for matrices
*   We can treat a list of lists as a matrix

In [4]:
z = [-1, 34, 21, 43]

In [5]:
z[1]

34

In [6]:
A = [[-1, 34, 21, 43], [ 2, -8, 99, 67], [ 5,  6, 7,  1]]
A

[[-1, 34, 21, 43], [2, -8, 99, 67], [5, 6, 7, 1]]

In [7]:
type(A) 

list

In [8]:
A[0]

[-1, 34, 21, 43]

In [10]:
A[1][2] 

99

In [11]:
A

[[-1, 34, 21, 43], [2, -8, 99, 67], [5, 6, 7, 1]]

*   You can only grab rows of this data structure
*   You cannot grab columns

In [12]:
A + A #this will only concatenate 

[[-1, 34, 21, 43],
 [2, -8, 99, 67],
 [5, 6, 7, 1],
 [-1, 34, 21, 43],
 [2, -8, 99, 67],
 [5, 6, 7, 1]]

## Importing packages/libraries/functions/classes

In [13]:
#Importing the entire package/module:
import math

result = math.sqrt(16)
print(result)

4.0


In [14]:
#Importing specific functions/classes from a package/module:
from math import sqrt

result = sqrt(16)
print(result)

4.0


In [15]:
#Importing a package/module with an alias:
import math as m

result = m.sqrt(16)
print(result)

4.0


In [16]:
#Importing specific functions/classes from a package/module:
from math import sqrt as square_root

result = square_root(16)
print(result)

4.0


## Python Arrays

Arrays in Python are data structures that can hold multiple values of the same type

In [18]:
from array import *

In [19]:
a = array('d', [1.2, 1.3, 2.3]) # First entry is the data type, second entry is the list
print(a)                        # a is an array of float type values
print(type(a))
print(type(a[0]))

array('d', [1.2, 1.3, 2.3])
<class 'array.array'>
<class 'float'>


In [20]:
i = array('i', [1,2,3]) # Array of integers
print(i)

array('i', [1, 2, 3])


In [21]:
strg = array('u', 'abcde') # Array of characters
print(strg)

array('u', 'abcde')


Data types can be obtained: https://docs.python.org/3/library/array.html

**Is a Python list same as a Python array?**


*   Array stores single data type values while list stores collection of different data types.
*   Arrays are more efficient than lists. 


 



In [22]:
li = [1, 'a', 5.0, 'b']
print(li)
type(li)

[1, 'a', 5.0, 'b']


list

Arrays as mutable data structures

In [23]:
a = array('d', [1.2, 1.3, 2.3])

In [24]:
print(len(a)) # Length of array
print(a[1])   # Second element in array

3
1.3


In [26]:
a = array('i', [[1.2, 1.3, 2.3],[3.2, 3.3, 3.3]])
a

TypeError: 'list' object cannot be interpreted as an integer

In [27]:
a.append(3.2) # Append a new element of same data type
a

array('d', [1.2, 1.3, 2.3, 3.2])

In [31]:
a.extend([5.1,6]) # Add both 5.1 and 6.1
a

array('d', [1.2, 1.3, 2.3, 3.2, 5.1, 6.1, 5.1, 6.0, 5.1, 5.1, 6.0])

In [32]:
a.insert(2,8.1) # Insert 8.1 at index 2
a

array('d', [1.2, 1.3, 8.1, 2.3, 3.2, 5.1, 6.1, 5.1, 6.0, 5.1, 5.1, 6.0])

Concatenation

In [39]:
a= array('d',[1.1 , 2.1 ,3.1,2.6,7.8])
b= array('d',[3.7,8.6])
# c= array('i') #must define data type (float)

In [40]:
c = a + b
c

array('d', [1.1, 2.1, 3.1, 2.6, 7.8, 3.7, 8.6])

Removing elements

In [41]:
a= array('d', [1.1, 2.2, 3.8, 3.1, 3.7, 1.2, 4.6])
print(a.pop())   # Remove and return the last element
a

4.6


array('d', [1.1, 2.2, 3.8, 3.1, 3.7, 1.2])

In [42]:
print(a.pop(3))  # Remove and return the element at index 3
a

3.1


array('d', [1.1, 2.2, 3.8, 3.7, 1.2])

In [44]:
a.remove(1.2) # Remove element 1.1
a

array('d', [2.2, 3.8, 3.7])

In [48]:
a[0:2] # Slice an array (return at indexes 0,1 and 2)

array('d', [2.2, 3.8])

In [49]:
a = array('d', [[1.2, 1.3, 2.3],[3.2, 3.3, 3.3]])
a

TypeError: must be real number, not list

## Arrays in Numpy (Numerical Python)

*   NumPy is a package for scientific computing
*   NumPy provides support for a powerful N-dimensional array object
*   NumPy provides multidimensional array of numbers

**Python NumPy Array vs. List**


We use Python NumPy array instead of a list because of three reasons: less memory, fast computing, some convenience.

### Creating Numpy Arrays

In [51]:
import numpy as np

In [52]:
a = np.array([1,2,3]) # Creates an array
a

array([1, 2, 3])

In [53]:
a = np.array([(1,2,3), (4,5,6)]) # Creates a 2-dimensional matrix 2x2 (using tuples)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a = np.array([[1,2,3], [4,5,6]]) # Another way of creating 2-dim matrix (using lists)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
a=np.array([(1,2,3,8), (8,2,4,1)], dtype=np.float64) # Creates matrix with a declared data type
print(type(a))
print(type(a[1][2]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [56]:
np.ndim(a) # Returns the dimension of matrix

2

In [61]:
a = np.zeros((2,3)) # Creates a 2-dimensional matrix 2x3 filled with zeros
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
a = np.zeros((2, 3),dtype = np.int64)
a

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [68]:
a = np.ones((3,3)) # 3x3 matrix filled with ones
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
a = np.full((3,3), 10.51)
a

array([[10.51, 10.51, 10.51],
       [10.51, 10.51, 10.51],
       [10.51, 10.51, 10.51]])

### Accessing elements

In [77]:
a = np.array([(1,2,3),(4,5,6)]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
b = [[1, 2, 3], [4, 5, 6]]
b[0][1]

2

In [82]:
a[0,0] = 999 # Change an element
a

array([[999,   2,   3],
       [  4,   5,   6]])

In [83]:
print(a[1][1]) # Returns element 5
print(a[1,1])

5
5


In [88]:
a[1,:] # Rreturns second row

array([4, 5, 6])

In [89]:
a[:,0] # Returns second column

array([999,   4])

In [90]:
a = np.array([[ 1,  4,  5, 12],
              [-5,  8,  9,  0],
              [-6,  7, 11, 19]])
a


array([[ 1,  4,  5, 12],
       [-5,  8,  9,  0],
       [-6,  7, 11, 19]])

In [91]:
a[2,1:4] # Slicing method. From 3rd row return elements at 2nd and 3rd array of [7,11,19]

array([ 7, 11, 19])

In [92]:
a[2][1:4]  # Slicing method. From 3rd row return elements at 2nd and 3rd array of [7,11,19]

array([ 7, 11, 19])

In [93]:
a[:,0:2] # Return all rows and 1st and 2nd columns.

array([[ 1,  4],
       [-5,  8],
       [-6,  7]])

### Performing operations 

In [108]:
arr1 = np.array([[1, 2, 3],
                 [1, 2, 3],
                [1, 2, 3]])

arr2 = np.array([[4, 5, 6],
                 [4, 5, 6],
                 [4, 5, 6]])

In [99]:
# Adding two arrays
result = arr1 + arr2
print(result)  

[[5 7 9]
 [5 7 9]
 [5 7 9]]


In [104]:
# Multiplying arrays element-wise
result = arr1 * arr2
print(result)  

[[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]]


In [109]:
# Matrix Multiplication
result = np.matmul(arr1, arr2)
print(result)  

[[24 30 36]
 [24 30 36]
 [24 30 36]]


In [111]:
arr1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [110]:
# Computing the square root of each element
result = np.sqrt(arr1)
print(result)

[[1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]]


In [112]:
# Computing the sum of all elements
result = np.sum(arr1)
print(result)

18


In [129]:
arr1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
arr1 = arr1-1
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [131]:
# Reshaping the array
reshaped_arr = arr1.reshape((8,-1))
print(reshaped_arr)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [138]:
# Transposing the array
transposed_arr = np.transpose(arr1).T
print(transposed_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [148]:
# Generating random integers between 0 and 9
random_arr = np.random.randint(low=1, high=10, size=(3, 3))
print(random_arr)

[[5 4 9]
 [2 7 1]
 [4 4 3]]


In [160]:
# Generating random numbers from a standard normal distribution
random_numbers = np.random.randn(5,2)
print(random_numbers)

[[ 1.23136916  0.32230225]
 [ 0.85820001 -0.17012683]
 [ 1.65183085  1.47611942]
 [-0.75628509  0.02255615]
 [-1.40149046  0.67104586]]
